//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiIntegrationTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://st1login.servicechannel.com/oauth/token")]
        public string ServerNameLogin {
            get {
                return ((string)(this["ServerNameLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("st1.servicechannel.com")]
        public string ServerNameApi {
            get {
                return ((string)(this["ServerNameApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sc_internal_api_documentation")]
        public string ClientId {
            get {
                return ((string)(this["ClientId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BAD4554B-AAE5-404B-8277-7F3D921B3EFC")]
        public string ClientSecret {
            get {
                return ((string)(this["ClientSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("demo")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d3m0")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c2NfaW50ZXJuYWxfYXBpX2RvY3VtZW50YXRpb246QkFENDU1NEItQUFFNS00MDRCLTgyNzctN0YzRDkyM" +
            "UIzRUZD")]
        public string AuthBasic {
            get {
                return ((string)(this["AuthBasic"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0""?><DATA2SC PIN=""40487"" ID=""942842206""><CALL DATETIME=""2016/12/30 11:03:39"" OPERATOR=""BulkPMDispatcher"" CALLER=""PM XML Interface"" CATEGORY=""Maintenance"" SUB=""2000001305"" LOC=""2310"" TRADE=""FLOOR MAINTENANCE-WOOD"" WO_NUM=""12942866"" PO_NUM=""12942866"" STATUS=""OPEN"" PRIORITY=""P7 (Routine &amp; PM)"" CURRENCY=""USD""><PROBLEM>Test</PROBLEM></CALL></DATA2SC>")]
        public string XML {
            get {
                return ((string)(this["XML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"%3C%3Fxml%20version%3D%221.0%22%3F%3E%3CDATA2SC%20PIN%3D%2240487%22%20ID%3D%22942842206%22%3E%3CCALL%20DATETIME%3D%222016/12/30%2011%3A03%3A39%22%20OPERATOR%3D%22BulkPMDispatcher%22%20CALLER%3D%22PM%20XML%20Interface%22%20CATEGORY%3D%22Maintenance%22%20SUB%3D%222000001305%22%20LOC%3D%222310%22%20TRADE%3D%22FLOOR%20MAINTENANCE-WOOD%22%20WO_NUM%3D%2212942867%22%20PO_NUM%3D%2212942867%22%20STATUS%3D%22OPEN%22%20PRIORITY%3D%22P7%20%28Routine%20%26amp%3B%20PM%29%22%20CURRENCY%3D%22USD%22%3E%3CPROBLEM%3ETest%3C/PROBLEM%3E%3C/CALL%3E%3C/DATA2SC%3E")]
        public string XML_code {
            get {
                return ((string)(this["XML_code"]));
            }
        }
    }
}
